name: React Firebase CI/CD

on:
  push:
    # branches: [master]
    branches: - main
  pull_request:
    # branches: [master]
    branches: - master

jobs:
  build_test_deploy:
    # runs-on: ubuntu-18.04
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Install Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14.15.1

      # - name: Install Dependencies
      #   run: |
      #     yarn install
      #   working-directory: app
      - name: Install Dependencies
        run: npm install

      - name: Build
        # run: |
        #   yarn build
        # working-directory: app
        run: npm run build

      # - name: Test
      #   run: |
      #     yarn test
      #   working-directory: app

      # - name: Install Firebase Tools
      #   run: |
      #     npm install -g firebase-tools
      #   working-directory: app

      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy  --only hosting --token $FIREBASE_TOKEN
        # working-directory: app
